package sv.edu.udb.pokebattle.service;
import java.time.LocalDateTime; import java.util.*;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import sv.edu.udb.pokebattle.dto.*; import sv.edu.udb.pokebattle.exception.*; import sv.edu.udb.pokebattle.model.*; import sv.edu.udb.pokebattle.repository.*;
@Service @RequiredArgsConstructor @Transactional public class CombateService {
 private final PartidaRepository partidas; private final ParticipantePartidaRepository participantes; private final PokemonBatallaRepository batallas; private final MovimientoSeleccionadoRepository movimientos;
 @Transactional(readOnly=true) public EstadoPartidaResponse estado(UUID id){Partida p=partida(id); return new EstadoPartidaResponse(p.getId(),p.getCodigoSala(),p.getEstado(),p.getNumeroTurno(),uid(p.getTurnoDe()),uid(p.getGanador()),participantes.findByPartidaId(id).stream().map(x->new EstadoParticipanteResponse(x.getJugador().getId(),x.getJugador().getNombre(),x.isConfirmado(),batallas.findByParticipantePartidaIdAndParticipanteJugadorId(id,x.getJugador().getId()).stream().map(PokemonBatallaResponse::desde).toList())).toList());}
 @Transactional(readOnly=true) public TurnoActualResponse turno(UUID id){Partida p=partida(id); enCurso(p); return new TurnoActualResponse(id,p.getNumeroTurno(),p.getTurnoDe().getId(),p.getTurnoDe().getNombre());}
 public AccionCombateResponse atacar(UUID id,AtacarRequest d){Partida p=partida(id); turnoValido(p,d.jugadorId()); PokemonBatalla a=activo(id,d.jugadorId()); MovimientoSeleccionado m=movimientos.findById(d.movimientoId()).orElseThrow(()->new RecursoNoEncontradoException("Movimiento no encontrado")); if(!m.getPokemon().getId().equals(a.getPokemonEquipo().getId()))throw new ReglaNegocioException("El movimiento no pertenece al Pokémon activo"); ParticipantePartida op=oponente(id,d.jugadorId()); PokemonBatalla def=activo(id,op.getJugador().getId()); int dano=Math.max(1,((a.getPokemonEquipo().getAtaqueBase()*(m.getPoder()==null?10:m.getPoder()))/100)-(def.getPokemonEquipo().getDefensaBase()/10)); def.setVidaActual(Math.max(0,def.getVidaActual()-dano)); boolean deb=def.getVidaActual()==0; if(deb){def.setDebilitado(true);def.setActivo(false);} batallas.save(def); if(deb&&!activar(id,op.getJugador().getId())) finalizar(p,a.getParticipante().getJugador()); else avanzar(p,op.getJugador()); partidas.save(p);return respuesta(p,TipoAccion.ATAQUE,d.jugadorId(),"Ataque procesado",dano,def.getVidaActual(),deb);}
 public AccionCombateResponse cambiar(UUID id,CambiarPokemonRequest d){Partida p=partida(id);turnoValido(p,d.jugadorId());PokemonBatalla actual=activo(id,d.jugadorId());PokemonBatalla destino=batallas.findByParticipantePartidaIdAndParticipanteJugadorId(id,d.jugadorId()).stream().filter(x->x.getPokemonEquipo().getId().equals(d.pokemonEquipoId())).findFirst().orElseThrow(()->new RecursoNoEncontradoException("Pokémon no encontrado en la partida"));if(destino.isDebilitado())throw new ReglaNegocioException("El Pokémon está debilitado");if(destino.isActivo())throw new ConflictoException("El Pokémon ya está activo");actual.setActivo(false);destino.setActivo(true);batallas.saveAll(List.of(actual,destino));avanzar(p,oponente(id,d.jugadorId()).getJugador());partidas.save(p);return respuesta(p,TipoAccion.CAMBIO_POKEMON,d.jugadorId(),"Pokémon cambiado",0,destino.getVidaActual(),false);}
 public AccionCombateResponse rendirse(UUID id,RendirseRequest d){Partida p=partida(id);enCurso(p);participante(id,d.jugadorId());finalizar(p,oponente(id,d.jugadorId()).getJugador());partidas.save(p);return respuesta(p,TipoAccion.RENDICION,d.jugadorId(),"Partida finalizada por rendición",0,null,false);}
 private boolean activar(UUID id,UUID jugador){return batallas.findByParticipantePartidaIdAndParticipanteJugadorIdAndDebilitadoFalse(id,jugador).stream().filter(x->!x.isActivo()).findFirst().map(x->{x.setActivo(true);batallas.save(x);return true;}).orElse(false);} private void avanzar(Partida p,Jugador j){p.setNumeroTurno(p.getNumeroTurno()+1);p.setTurnoDe(j);} private void finalizar(Partida p,Jugador ganador){p.setEstado(EstadoPartida.FINALIZADA);p.setGanador(ganador);p.setTurnoDe(null);p.setFinalizadaEn(LocalDateTime.now());} private void turnoValido(Partida p,UUID j){enCurso(p);if(!p.getTurnoDe().getId().equals(j))throw new ConflictoException("No corresponde al turno del jugador");} private void enCurso(Partida p){if(p.getEstado()!=EstadoPartida.EN_CURSO)throw new ConflictoException("La partida no está en curso");} private PokemonBatalla activo(UUID p,UUID j){return batallas.findByParticipantePartidaIdAndParticipanteJugadorIdAndActivoTrue(p,j).orElseThrow(()->new ConflictoException("El jugador no posee un Pokémon activo"));} private ParticipantePartida participante(UUID p,UUID j){return participantes.findByPartidaIdAndJugadorId(p,j).orElseThrow(()->new RecursoNoEncontradoException("Participante no encontrado"));} private ParticipantePartida oponente(UUID p,UUID j){return participantes.findByPartidaId(p).stream().filter(x->!x.getJugador().getId().equals(j)).findFirst().orElseThrow(()->new ConflictoException("La partida no posee un oponente"));} private Partida partida(UUID id){return partidas.findById(id).orElseThrow(()->new RecursoNoEncontradoException("Partida no encontrada"));} private UUID uid(Jugador j){return j==null?null:j.getId();} private AccionCombateResponse respuesta(Partida p,TipoAccion t,UUID j,String msg,Integer d,Integer v,boolean deb){return new AccionCombateResponse(p.getNumeroTurno(),t,j,msg,d,v,deb,p.getEstado(),uid(p.getTurnoDe()),uid(p.getGanador()));}
}
